runtime: java
vm: true

#runtime_config:  # Optional
#  jdk: openjdk8

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always  # Require HTTPS

#manual_scaling:
#  instances: 1